/**
Do not edit directly
This file was generated by 'build-tokens.js' on
2024-06-16T08:55:43.109Z
*/


      import * as stylex from '@stylexjs/stylex'; 
      export const tokens = stylex.defineVars({
  "Primary": {
    "Primary 100%": {
      "value": "#e86c00",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c00",
        "type": "color"
      },
      "name": "PrimaryPrimary100",
      "attributes": {
        "category": "Primary",
        "type": "Primary 100%"
      },
      "path": [
        "Primary",
        "Primary 100%"
      ]
    },
    "Primary 90%": {
      "value": "#e86c00e6",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c00e6",
        "type": "color"
      },
      "name": "PrimaryPrimary90",
      "attributes": {
        "category": "Primary",
        "type": "Primary 90%"
      },
      "path": [
        "Primary",
        "Primary 90%"
      ]
    },
    "Primary 80%": {
      "value": "#e86c00cc",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c00cc",
        "type": "color"
      },
      "name": "PrimaryPrimary80",
      "attributes": {
        "category": "Primary",
        "type": "Primary 80%"
      },
      "path": [
        "Primary",
        "Primary 80%"
      ]
    },
    "Primary 70%": {
      "value": "#e86c00b3",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c00b3",
        "type": "color"
      },
      "name": "PrimaryPrimary70",
      "attributes": {
        "category": "Primary",
        "type": "Primary 70%"
      },
      "path": [
        "Primary",
        "Primary 70%"
      ]
    },
    "Primary 60%": {
      "value": "#e86c0099",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c0099",
        "type": "color"
      },
      "name": "PrimaryPrimary60",
      "attributes": {
        "category": "Primary",
        "type": "Primary 60%"
      },
      "path": [
        "Primary",
        "Primary 60%"
      ]
    },
    "Primary 50%": {
      "value": "#e86c0080",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c0080",
        "type": "color"
      },
      "name": "PrimaryPrimary50",
      "attributes": {
        "category": "Primary",
        "type": "Primary 50%"
      },
      "path": [
        "Primary",
        "Primary 50%"
      ]
    },
    "Primary 40%": {
      "value": "#e86c0066",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c0066",
        "type": "color"
      },
      "name": "PrimaryPrimary40",
      "attributes": {
        "category": "Primary",
        "type": "Primary 40%"
      },
      "path": [
        "Primary",
        "Primary 40%"
      ]
    },
    "Primary 30%": {
      "value": "#e86c004d",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c004d",
        "type": "color"
      },
      "name": "PrimaryPrimary30",
      "attributes": {
        "category": "Primary",
        "type": "Primary 30%"
      },
      "path": [
        "Primary",
        "Primary 30%"
      ]
    },
    "Primary 20%": {
      "value": "#e86c0033",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c0033",
        "type": "color"
      },
      "name": "PrimaryPrimary20",
      "attributes": {
        "category": "Primary",
        "type": "Primary 20%"
      },
      "path": [
        "Primary",
        "Primary 20%"
      ]
    },
    "Primary 10%": {
      "value": "#e86c001a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c001a",
        "type": "color"
      },
      "name": "PrimaryPrimary10",
      "attributes": {
        "category": "Primary",
        "type": "Primary 10%"
      },
      "path": [
        "Primary",
        "Primary 10%"
      ]
    }
  },
  "Secondary": {
    "Secondary 100%": {
      "value": "#fdcc4a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a",
        "type": "color"
      },
      "name": "SecondarySecondary100",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 100%"
      },
      "path": [
        "Secondary",
        "Secondary 100%"
      ]
    },
    "Secondary 90%": {
      "value": "#fdcc4ae6",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4ae6",
        "type": "color"
      },
      "name": "SecondarySecondary90",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 90%"
      },
      "path": [
        "Secondary",
        "Secondary 90%"
      ]
    },
    "Secondary 80%": {
      "value": "#fdcc4acc",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4acc",
        "type": "color"
      },
      "name": "SecondarySecondary80",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 80%"
      },
      "path": [
        "Secondary",
        "Secondary 80%"
      ]
    },
    "Secondary 70%": {
      "value": "#fdcc4ab3",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4ab3",
        "type": "color"
      },
      "name": "SecondarySecondary70",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 70%"
      },
      "path": [
        "Secondary",
        "Secondary 70%"
      ]
    },
    "Secondary 60%": {
      "value": "#fdcc4a99",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a99",
        "type": "color"
      },
      "name": "SecondarySecondary60",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 60%"
      },
      "path": [
        "Secondary",
        "Secondary 60%"
      ]
    },
    "Secondary 50%": {
      "value": "#fdcc4a80",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a80",
        "type": "color"
      },
      "name": "SecondarySecondary50",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 50%"
      },
      "path": [
        "Secondary",
        "Secondary 50%"
      ]
    },
    "Secondary 40%": {
      "value": "#fdcc4a66",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a66",
        "type": "color"
      },
      "name": "SecondarySecondary40",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 40%"
      },
      "path": [
        "Secondary",
        "Secondary 40%"
      ]
    },
    "Secondary 30%": {
      "value": "#fdcc4a4d",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a4d",
        "type": "color"
      },
      "name": "SecondarySecondary30",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 30%"
      },
      "path": [
        "Secondary",
        "Secondary 30%"
      ]
    },
    "Secondary 20%": {
      "value": "#fdcc4a33",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a33",
        "type": "color"
      },
      "name": "SecondarySecondary20",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 20%"
      },
      "path": [
        "Secondary",
        "Secondary 20%"
      ]
    },
    "Secondary 10%": {
      "value": "#fdcc4a1a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fdcc4a1a",
        "type": "color"
      },
      "name": "SecondarySecondary10",
      "attributes": {
        "category": "Secondary",
        "type": "Secondary 10%"
      },
      "path": [
        "Secondary",
        "Secondary 10%"
      ]
    }
  },
  "Neutral": {
    "Black": {
      "value": "#09101d",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#09101d",
        "type": "color"
      },
      "name": "NeutralBlack",
      "attributes": {
        "category": "Neutral",
        "type": "Black"
      },
      "path": [
        "Neutral",
        "Black"
      ]
    },
    "Neutral 1": {
      "value": "#2c3a4b",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#2c3a4b",
        "type": "color"
      },
      "name": "NeutralNeutral1",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 1"
      },
      "path": [
        "Neutral",
        "Neutral 1"
      ]
    },
    "Neutral 2": {
      "value": "#394452",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#394452",
        "type": "color"
      },
      "name": "NeutralNeutral2",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 2"
      },
      "path": [
        "Neutral",
        "Neutral 2"
      ]
    },
    "Neutral 3": {
      "value": "#545d69",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#545d69",
        "type": "color"
      },
      "name": "NeutralNeutral3",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 3"
      },
      "path": [
        "Neutral",
        "Neutral 3"
      ]
    },
    "Neutral 4": {
      "value": "#6d7580",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#6d7580",
        "type": "color"
      },
      "name": "NeutralNeutral4",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 4"
      },
      "path": [
        "Neutral",
        "Neutral 4"
      ]
    },
    "Neutral 5": {
      "description": "Icon default color",
      "value": "#858c94",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "description": "Icon default color",
        "value": "#858c94",
        "type": "color"
      },
      "name": "NeutralNeutral5",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 5"
      },
      "path": [
        "Neutral",
        "Neutral 5"
      ]
    },
    "Neutral 6": {
      "description": "Disabled Action",
      "value": "#a5abb3",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "description": "Disabled Action",
        "value": "#a5abb3",
        "type": "color"
      },
      "name": "NeutralNeutral6",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 6"
      },
      "path": [
        "Neutral",
        "Neutral 6"
      ]
    },
    "Neutral 7": {
      "value": "#dadee3",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#dadee3",
        "type": "color"
      },
      "name": "NeutralNeutral7",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 7"
      },
      "path": [
        "Neutral",
        "Neutral 7"
      ]
    },
    "Neutral 8": {
      "value": "#ebeef2",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ebeef2",
        "type": "color"
      },
      "name": "NeutralNeutral8",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 8"
      },
      "path": [
        "Neutral",
        "Neutral 8"
      ]
    },
    "Neutral 9": {
      "value": "#f4f6f9",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#f4f6f9",
        "type": "color"
      },
      "name": "NeutralNeutral9",
      "attributes": {
        "category": "Neutral",
        "type": "Neutral 9"
      },
      "path": [
        "Neutral",
        "Neutral 9"
      ]
    },
    "White": {
      "value": "#ffffff",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ffffff",
        "type": "color"
      },
      "name": "NeutralWhite",
      "attributes": {
        "category": "Neutral",
        "type": "White"
      },
      "path": [
        "Neutral",
        "White"
      ]
    }
  },
  "Accent": {
    "Accent 1": {
      "value": "#ecb2f2",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ecb2f2",
        "type": "color"
      },
      "name": "AccentAccent1",
      "attributes": {
        "category": "Accent",
        "type": "Accent 1"
      },
      "path": [
        "Accent",
        "Accent 1"
      ]
    },
    "Accent 1 28%": {
      "value": "#ecb2f247",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ecb2f247",
        "type": "color"
      },
      "name": "AccentAccent128",
      "attributes": {
        "category": "Accent",
        "type": "Accent 1 28%"
      },
      "path": [
        "Accent",
        "Accent 1 28%"
      ]
    },
    "Accent 2": {
      "value": "#2d6a6a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#2d6a6a",
        "type": "color"
      },
      "name": "AccentAccent2",
      "attributes": {
        "category": "Accent",
        "type": "Accent 2"
      },
      "path": [
        "Accent",
        "Accent 2"
      ]
    },
    "Accent 2 10%": {
      "value": "#2d6a6a1a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#2d6a6a1a",
        "type": "color"
      },
      "name": "AccentAccent210",
      "attributes": {
        "category": "Accent",
        "type": "Accent 2 10%"
      },
      "path": [
        "Accent",
        "Accent 2 10%"
      ]
    },
    "Accent 3": {
      "value": "#e9ad8c",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e9ad8c",
        "type": "color"
      },
      "name": "AccentAccent3",
      "attributes": {
        "category": "Accent",
        "type": "Accent 3"
      },
      "path": [
        "Accent",
        "Accent 3"
      ]
    },
    "Accent 3 23%": {
      "value": "#e9ad8c3b",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e9ad8c3b",
        "type": "color"
      },
      "name": "AccentAccent323",
      "attributes": {
        "category": "Accent",
        "type": "Accent 3 23%"
      },
      "path": [
        "Accent",
        "Accent 3 23%"
      ]
    },
    "Accent 4": {
      "value": "#221874",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#221874",
        "type": "color"
      },
      "name": "AccentAccent4",
      "attributes": {
        "category": "Accent",
        "type": "Accent 4"
      },
      "path": [
        "Accent",
        "Accent 4"
      ]
    },
    "Accent 4 10%": {
      "value": "#2218741a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#2218741a",
        "type": "color"
      },
      "name": "AccentAccent410",
      "attributes": {
        "category": "Accent",
        "type": "Accent 4 10%"
      },
      "path": [
        "Accent",
        "Accent 4 10%"
      ]
    },
    "Accent 5": {
      "value": "#7cc6d6",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#7cc6d6",
        "type": "color"
      },
      "name": "AccentAccent5",
      "attributes": {
        "category": "Accent",
        "type": "Accent 5"
      },
      "path": [
        "Accent",
        "Accent 5"
      ]
    },
    "Accent 5 25%": {
      "value": "#7cc6d640",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#7cc6d640",
        "type": "color"
      },
      "name": "AccentAccent525",
      "attributes": {
        "category": "Accent",
        "type": "Accent 5 25%"
      },
      "path": [
        "Accent",
        "Accent 5 25%"
      ]
    },
    "Accent 6": {
      "value": "#e1604d",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e1604d",
        "type": "color"
      },
      "name": "AccentAccent6",
      "attributes": {
        "category": "Accent",
        "type": "Accent 6"
      },
      "path": [
        "Accent",
        "Accent 6"
      ]
    },
    "Accent 6 15%": {
      "value": "#e1604d26",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e1604d26",
        "type": "color"
      },
      "name": "AccentAccent615",
      "attributes": {
        "category": "Accent",
        "type": "Accent 6 15%"
      },
      "path": [
        "Accent",
        "Accent 6 15%"
      ]
    }
  },
  "Status": {
    "Success": {
      "value": "#287d3c",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#287d3c",
        "type": "color"
      },
      "name": "StatusSuccess",
      "attributes": {
        "category": "Status",
        "type": "Success"
      },
      "path": [
        "Status",
        "Success"
      ]
    },
    "Success BG": {
      "value": "#edf9f0",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#edf9f0",
        "type": "color"
      },
      "name": "StatusSuccessBg",
      "attributes": {
        "category": "Status",
        "type": "Success BG"
      },
      "path": [
        "Status",
        "Success BG"
      ]
    },
    "Warning": {
      "value": "#b95000",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#b95000",
        "type": "color"
      },
      "name": "StatusWarning",
      "attributes": {
        "category": "Status",
        "type": "Warning"
      },
      "path": [
        "Status",
        "Warning"
      ]
    },
    "Warning BG": {
      "value": "#fff4ec",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#fff4ec",
        "type": "color"
      },
      "name": "StatusWarningBg",
      "attributes": {
        "category": "Status",
        "type": "Warning BG"
      },
      "path": [
        "Status",
        "Warning BG"
      ]
    },
    "Error": {
      "value": "#da1414",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#da1414",
        "type": "color"
      },
      "name": "StatusError",
      "attributes": {
        "category": "Status",
        "type": "Error"
      },
      "path": [
        "Status",
        "Error"
      ]
    },
    "Error BG": {
      "value": "#feefef",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#feefef",
        "type": "color"
      },
      "name": "StatusErrorBg",
      "attributes": {
        "category": "Status",
        "type": "Error BG"
      },
      "path": [
        "Status",
        "Error BG"
      ]
    },
    "Info": {
      "value": "#2e5aac",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#2e5aac",
        "type": "color"
      },
      "name": "StatusInfo",
      "attributes": {
        "category": "Status",
        "type": "Info"
      },
      "path": [
        "Status",
        "Info"
      ]
    },
    "Info BG": {
      "value": "#eef2fa",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#eef2fa",
        "type": "color"
      },
      "name": "StatusInfoBg",
      "attributes": {
        "category": "Status",
        "type": "Info BG"
      },
      "path": [
        "Status",
        "Info BG"
      ]
    }
  },
  "Action Primary": {
    "Default": {
      "value": "#e86c00",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c00",
        "type": "color"
      },
      "name": "ActionPrimaryDefault",
      "attributes": {
        "category": "Action Primary",
        "type": "Default"
      },
      "path": [
        "Action Primary",
        "Default"
      ]
    },
    "Hover": {
      "value": "#cc5f00",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#cc5f00",
        "type": "color"
      },
      "name": "ActionPrimaryHover",
      "attributes": {
        "category": "Action Primary",
        "type": "Hover"
      },
      "path": [
        "Action Primary",
        "Hover"
      ]
    },
    "Active": {
      "value": "#b25300",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#b25300",
        "type": "color"
      },
      "name": "ActionPrimaryActive",
      "attributes": {
        "category": "Action Primary",
        "type": "Active"
      },
      "path": [
        "Action Primary",
        "Active"
      ]
    },
    "Disabled": {
      "value": "#e86c0080",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#e86c0080",
        "type": "color"
      },
      "name": "ActionPrimaryDisabled",
      "attributes": {
        "category": "Action Primary",
        "type": "Disabled"
      },
      "path": [
        "Action Primary",
        "Disabled"
      ]
    },
    "Hover 10%": {
      "value": "#cc5f001a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#cc5f001a",
        "type": "color"
      },
      "name": "ActionPrimaryHover10",
      "attributes": {
        "category": "Action Primary",
        "type": "Hover 10%"
      },
      "path": [
        "Action Primary",
        "Hover 10%"
      ]
    },
    "Active 20%": {
      "value": "#b2530033",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#b2530033",
        "type": "color"
      },
      "name": "ActionPrimaryActive20",
      "attributes": {
        "category": "Action Primary",
        "type": "Active 20%"
      },
      "path": [
        "Action Primary",
        "Active 20%"
      ]
    },
    "Inverted": {
      "value": "#ffffff",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ffffff",
        "type": "color"
      },
      "name": "ActionPrimaryInverted",
      "attributes": {
        "category": "Action Primary",
        "type": "Inverted"
      },
      "path": [
        "Action Primary",
        "Inverted"
      ]
    },
    "Visited": {
      "value": "#5e38ba",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#5e38ba",
        "type": "color"
      },
      "name": "ActionPrimaryVisited",
      "attributes": {
        "category": "Action Primary",
        "type": "Visited"
      },
      "path": [
        "Action Primary",
        "Visited"
      ]
    }
  },
  "Action Secondary": {
    "Default": {
      "value": "#19ab4f",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#19ab4f",
        "type": "color"
      },
      "name": "ActionSecondaryDefault",
      "attributes": {
        "category": "Action Secondary",
        "type": "Default"
      },
      "path": [
        "Action Secondary",
        "Default"
      ]
    },
    "Hover": {
      "value": "#0c9e42",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#0c9e42",
        "type": "color"
      },
      "name": "ActionSecondaryHover",
      "attributes": {
        "category": "Action Secondary",
        "type": "Hover"
      },
      "path": [
        "Action Secondary",
        "Hover"
      ]
    },
    "Active": {
      "value": "#009236",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#009236",
        "type": "color"
      },
      "name": "ActionSecondaryActive",
      "attributes": {
        "category": "Action Secondary",
        "type": "Active"
      },
      "path": [
        "Action Secondary",
        "Active"
      ]
    },
    "Disabled": {
      "value": "#19ab4f80",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#19ab4f80",
        "type": "color"
      },
      "name": "ActionSecondaryDisabled",
      "attributes": {
        "category": "Action Secondary",
        "type": "Disabled"
      },
      "path": [
        "Action Secondary",
        "Disabled"
      ]
    },
    "Hover 10%": {
      "value": "#0c9d411a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#0c9d411a",
        "type": "color"
      },
      "name": "ActionSecondaryHover10",
      "attributes": {
        "category": "Action Secondary",
        "type": "Hover 10%"
      },
      "path": [
        "Action Secondary",
        "Hover 10%"
      ]
    },
    "Active 20%": {
      "value": "#00943633",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#00943633",
        "type": "color"
      },
      "name": "ActionSecondaryActive20",
      "attributes": {
        "category": "Action Secondary",
        "type": "Active 20%"
      },
      "path": [
        "Action Secondary",
        "Active 20%"
      ]
    },
    "Inverted": {
      "value": "#ffffff",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ffffff",
        "type": "color"
      },
      "name": "ActionSecondaryInverted",
      "attributes": {
        "category": "Action Secondary",
        "type": "Inverted"
      },
      "path": [
        "Action Secondary",
        "Inverted"
      ]
    },
    "Visited": {
      "value": "#5e38ba",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#5e38ba",
        "type": "color"
      },
      "name": "ActionSecondaryVisited",
      "attributes": {
        "category": "Action Secondary",
        "type": "Visited"
      },
      "path": [
        "Action Secondary",
        "Visited"
      ]
    }
  },
  "Action Neutral": {
    "Default": {
      "value": "#9098a1",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#9098a1",
        "type": "color"
      },
      "name": "ActionNeutralDefault",
      "attributes": {
        "category": "Action Neutral",
        "type": "Default"
      },
      "path": [
        "Action Neutral",
        "Default"
      ]
    },
    "Hover": {
      "value": "#858c94",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#858c94",
        "type": "color"
      },
      "name": "ActionNeutralHover",
      "attributes": {
        "category": "Action Neutral",
        "type": "Hover"
      },
      "path": [
        "Action Neutral",
        "Hover"
      ]
    },
    "Active": {
      "value": "#798087",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#798087",
        "type": "color"
      },
      "name": "ActionNeutralActive",
      "attributes": {
        "category": "Action Neutral",
        "type": "Active"
      },
      "path": [
        "Action Neutral",
        "Active"
      ]
    },
    "Disabled": {
      "value": "#9098a1b3",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#9098a1b3",
        "type": "color"
      },
      "name": "ActionNeutralDisabled",
      "attributes": {
        "category": "Action Neutral",
        "type": "Disabled"
      },
      "path": [
        "Action Neutral",
        "Disabled"
      ]
    },
    "Hover 10%": {
      "value": "#6d75801a",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#6d75801a",
        "type": "color"
      },
      "name": "ActionNeutralHover10",
      "attributes": {
        "category": "Action Neutral",
        "type": "Hover 10%"
      },
      "path": [
        "Action Neutral",
        "Hover 10%"
      ]
    },
    "Active 20%": {
      "value": "#6d758033",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#6d758033",
        "type": "color"
      },
      "name": "ActionNeutralActive20",
      "attributes": {
        "category": "Action Neutral",
        "type": "Active 20%"
      },
      "path": [
        "Action Neutral",
        "Active 20%"
      ]
    },
    "Inverted": {
      "value": "#ffffff",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#ffffff",
        "type": "color"
      },
      "name": "ActionNeutralInverted",
      "attributes": {
        "category": "Action Neutral",
        "type": "Inverted"
      },
      "path": [
        "Action Neutral",
        "Inverted"
      ]
    },
    "Visited": {
      "value": "#5e38ba",
      "type": "color",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "#5e38ba",
        "type": "color"
      },
      "name": "ActionNeutralVisited",
      "attributes": {
        "category": "Action Neutral",
        "type": "Visited"
      },
      "path": [
        "Action Neutral",
        "Visited"
      ]
    }
  },
  "fontFamilies": {
    "source-sans-pro": {
      "value": "Source Sans Pro",
      "type": "fontFamilies",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "Source Sans Pro",
        "type": "fontFamilies"
      },
      "name": "FontFamiliesSourceSansPro",
      "attributes": {
        "category": "fontFamilies",
        "type": "source-sans-pro"
      },
      "path": [
        "fontFamilies",
        "source-sans-pro"
      ]
    },
    "inter": {
      "value": "Inter",
      "type": "fontFamilies",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "Inter",
        "type": "fontFamilies"
      },
      "name": "FontFamiliesInter",
      "attributes": {
        "category": "fontFamilies",
        "type": "inter"
      },
      "path": [
        "fontFamilies",
        "inter"
      ]
    }
  },
  "lineHeights": {
    "0": {
      "value": "76",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "76",
        "type": "lineHeights"
      },
      "name": "LineHeights0",
      "attributes": {
        "category": "lineHeights",
        "type": "0"
      },
      "path": [
        "lineHeights",
        "0"
      ]
    },
    "1": {
      "value": "56",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "56",
        "type": "lineHeights"
      },
      "name": "LineHeights1",
      "attributes": {
        "category": "lineHeights",
        "type": "1"
      },
      "path": [
        "lineHeights",
        "1"
      ]
    },
    "2": {
      "value": "48",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "48",
        "type": "lineHeights"
      },
      "name": "LineHeights2",
      "attributes": {
        "category": "lineHeights",
        "type": "2"
      },
      "path": [
        "lineHeights",
        "2"
      ]
    },
    "3": {
      "value": "64",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "64",
        "type": "lineHeights"
      },
      "name": "LineHeights3",
      "attributes": {
        "category": "lineHeights",
        "type": "3"
      },
      "path": [
        "lineHeights",
        "3"
      ]
    },
    "4": {
      "value": "40",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "40",
        "type": "lineHeights"
      },
      "name": "LineHeights4",
      "attributes": {
        "category": "lineHeights",
        "type": "4"
      },
      "path": [
        "lineHeights",
        "4"
      ]
    },
    "5": {
      "value": "52",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "52",
        "type": "lineHeights"
      },
      "name": "LineHeights5",
      "attributes": {
        "category": "lineHeights",
        "type": "5"
      },
      "path": [
        "lineHeights",
        "5"
      ]
    },
    "6": {
      "value": "44",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "44",
        "type": "lineHeights"
      },
      "name": "LineHeights6",
      "attributes": {
        "category": "lineHeights",
        "type": "6"
      },
      "path": [
        "lineHeights",
        "6"
      ]
    },
    "7": {
      "value": "36",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "36",
        "type": "lineHeights"
      },
      "name": "LineHeights7",
      "attributes": {
        "category": "lineHeights",
        "type": "7"
      },
      "path": [
        "lineHeights",
        "7"
      ]
    },
    "8": {
      "value": "32",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "32",
        "type": "lineHeights"
      },
      "name": "LineHeights8",
      "attributes": {
        "category": "lineHeights",
        "type": "8"
      },
      "path": [
        "lineHeights",
        "8"
      ]
    },
    "9": {
      "value": "28",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "28",
        "type": "lineHeights"
      },
      "name": "LineHeights9",
      "attributes": {
        "category": "lineHeights",
        "type": "9"
      },
      "path": [
        "lineHeights",
        "9"
      ]
    },
    "10": {
      "value": "24",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "24",
        "type": "lineHeights"
      },
      "name": "LineHeights10",
      "attributes": {
        "category": "lineHeights",
        "type": "10"
      },
      "path": [
        "lineHeights",
        "10"
      ]
    },
    "11": {
      "value": "20",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "20",
        "type": "lineHeights"
      },
      "name": "LineHeights11",
      "attributes": {
        "category": "lineHeights",
        "type": "11"
      },
      "path": [
        "lineHeights",
        "11"
      ]
    },
    "12": {
      "value": "16",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "16",
        "type": "lineHeights"
      },
      "name": "LineHeights12",
      "attributes": {
        "category": "lineHeights",
        "type": "12"
      },
      "path": [
        "lineHeights",
        "12"
      ]
    },
    "13": {
      "value": "12",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "12",
        "type": "lineHeights"
      },
      "name": "LineHeights13",
      "attributes": {
        "category": "lineHeights",
        "type": "13"
      },
      "path": [
        "lineHeights",
        "13"
      ]
    },
    "14": {
      "value": "AUTO",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "AUTO",
        "type": "lineHeights"
      },
      "name": "LineHeights14",
      "attributes": {
        "category": "lineHeights",
        "type": "14"
      },
      "path": [
        "lineHeights",
        "14"
      ]
    },
    "15": {
      "value": "72",
      "type": "lineHeights",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "72",
        "type": "lineHeights"
      },
      "name": "LineHeights15",
      "attributes": {
        "category": "lineHeights",
        "type": "15"
      },
      "path": [
        "lineHeights",
        "15"
      ]
    }
  },
  "fontSize": {
    "0": {
      "value": "9",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "9",
        "type": "fontSizes"
      },
      "name": "FontSize0",
      "attributes": {
        "category": "fontSize",
        "type": "0"
      },
      "path": [
        "fontSize",
        "0"
      ]
    },
    "1": {
      "value": "11",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "11",
        "type": "fontSizes"
      },
      "name": "FontSize1",
      "attributes": {
        "category": "fontSize",
        "type": "1"
      },
      "path": [
        "fontSize",
        "1"
      ]
    },
    "2": {
      "value": "13",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "13",
        "type": "fontSizes"
      },
      "name": "FontSize2",
      "attributes": {
        "category": "fontSize",
        "type": "2"
      },
      "path": [
        "fontSize",
        "2"
      ]
    },
    "3": {
      "value": "14",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "14",
        "type": "fontSizes"
      },
      "name": "FontSize3",
      "attributes": {
        "category": "fontSize",
        "type": "3"
      },
      "path": [
        "fontSize",
        "3"
      ]
    },
    "4": {
      "value": "16",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "16",
        "type": "fontSizes"
      },
      "name": "FontSize4",
      "attributes": {
        "category": "fontSize",
        "type": "4"
      },
      "path": [
        "fontSize",
        "4"
      ]
    },
    "5": {
      "value": "18",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "18",
        "type": "fontSizes"
      },
      "name": "FontSize5",
      "attributes": {
        "category": "fontSize",
        "type": "5"
      },
      "path": [
        "fontSize",
        "5"
      ]
    },
    "6": {
      "value": "19",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "19",
        "type": "fontSizes"
      },
      "name": "FontSize6",
      "attributes": {
        "category": "fontSize",
        "type": "6"
      },
      "path": [
        "fontSize",
        "6"
      ]
    },
    "7": {
      "value": "20",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "20",
        "type": "fontSizes"
      },
      "name": "FontSize7",
      "attributes": {
        "category": "fontSize",
        "type": "7"
      },
      "path": [
        "fontSize",
        "7"
      ]
    },
    "8": {
      "value": "21",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "21",
        "type": "fontSizes"
      },
      "name": "FontSize8",
      "attributes": {
        "category": "fontSize",
        "type": "8"
      },
      "path": [
        "fontSize",
        "8"
      ]
    },
    "9": {
      "value": "23",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "23",
        "type": "fontSizes"
      },
      "name": "FontSize9",
      "attributes": {
        "category": "fontSize",
        "type": "9"
      },
      "path": [
        "fontSize",
        "9"
      ]
    },
    "10": {
      "value": "24",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "24",
        "type": "fontSizes"
      },
      "name": "FontSize10",
      "attributes": {
        "category": "fontSize",
        "type": "10"
      },
      "path": [
        "fontSize",
        "10"
      ]
    },
    "11": {
      "value": "26",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "26",
        "type": "fontSizes"
      },
      "name": "FontSize11",
      "attributes": {
        "category": "fontSize",
        "type": "11"
      },
      "path": [
        "fontSize",
        "11"
      ]
    },
    "12": {
      "value": "28",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "28",
        "type": "fontSizes"
      },
      "name": "FontSize12",
      "attributes": {
        "category": "fontSize",
        "type": "12"
      },
      "path": [
        "fontSize",
        "12"
      ]
    },
    "13": {
      "value": "29",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "29",
        "type": "fontSizes"
      },
      "name": "FontSize13",
      "attributes": {
        "category": "fontSize",
        "type": "13"
      },
      "path": [
        "fontSize",
        "13"
      ]
    },
    "14": {
      "value": "32",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "32",
        "type": "fontSizes"
      },
      "name": "FontSize14",
      "attributes": {
        "category": "fontSize",
        "type": "14"
      },
      "path": [
        "fontSize",
        "14"
      ]
    },
    "15": {
      "value": "33",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "33",
        "type": "fontSizes"
      },
      "name": "FontSize15",
      "attributes": {
        "category": "fontSize",
        "type": "15"
      },
      "path": [
        "fontSize",
        "15"
      ]
    },
    "16": {
      "value": "36",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "36",
        "type": "fontSizes"
      },
      "name": "FontSize16",
      "attributes": {
        "category": "fontSize",
        "type": "16"
      },
      "path": [
        "fontSize",
        "16"
      ]
    },
    "17": {
      "value": "38",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "38",
        "type": "fontSizes"
      },
      "name": "FontSize17",
      "attributes": {
        "category": "fontSize",
        "type": "17"
      },
      "path": [
        "fontSize",
        "17"
      ]
    },
    "18": {
      "value": "40",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "40",
        "type": "fontSizes"
      },
      "name": "FontSize18",
      "attributes": {
        "category": "fontSize",
        "type": "18"
      },
      "path": [
        "fontSize",
        "18"
      ]
    },
    "19": {
      "value": "41",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "41",
        "type": "fontSizes"
      },
      "name": "FontSize19",
      "attributes": {
        "category": "fontSize",
        "type": "19"
      },
      "path": [
        "fontSize",
        "19"
      ]
    },
    "20": {
      "value": "44",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "44",
        "type": "fontSizes"
      },
      "name": "FontSize20",
      "attributes": {
        "category": "fontSize",
        "type": "20"
      },
      "path": [
        "fontSize",
        "20"
      ]
    },
    "21": {
      "value": "48",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "48",
        "type": "fontSizes"
      },
      "name": "FontSize21",
      "attributes": {
        "category": "fontSize",
        "type": "21"
      },
      "path": [
        "fontSize",
        "21"
      ]
    },
    "22": {
      "value": "51",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "51",
        "type": "fontSizes"
      },
      "name": "FontSize22",
      "attributes": {
        "category": "fontSize",
        "type": "22"
      },
      "path": [
        "fontSize",
        "22"
      ]
    },
    "23": {
      "value": "54",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "54",
        "type": "fontSizes"
      },
      "name": "FontSize23",
      "attributes": {
        "category": "fontSize",
        "type": "23"
      },
      "path": [
        "fontSize",
        "23"
      ]
    },
    "24": {
      "value": "57",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "57",
        "type": "fontSizes"
      },
      "name": "FontSize24",
      "attributes": {
        "category": "fontSize",
        "type": "24"
      },
      "path": [
        "fontSize",
        "24"
      ]
    },
    "25": {
      "value": "69",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "69",
        "type": "fontSizes"
      },
      "name": "FontSize25",
      "attributes": {
        "category": "fontSize",
        "type": "25"
      },
      "path": [
        "fontSize",
        "25"
      ]
    },
    "26": {
      "value": "160",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "160",
        "type": "fontSizes"
      },
      "name": "FontSize26",
      "attributes": {
        "category": "fontSize",
        "type": "26"
      },
      "path": [
        "fontSize",
        "26"
      ]
    },
    "27": {
      "value": "560",
      "type": "fontSizes",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "560",
        "type": "fontSizes"
      },
      "name": "FontSize27",
      "attributes": {
        "category": "fontSize",
        "type": "27"
      },
      "path": [
        "fontSize",
        "27"
      ]
    }
  },
  "letterSpacing": {
    "0": {
      "value": "0%",
      "type": "letterSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "0%",
        "type": "letterSpacing"
      },
      "name": "LetterSpacing0",
      "attributes": {
        "category": "letterSpacing",
        "type": "0"
      },
      "path": [
        "letterSpacing",
        "0"
      ]
    },
    "1": {
      "value": "5%",
      "type": "letterSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "5%",
        "type": "letterSpacing"
      },
      "name": "LetterSpacing1",
      "attributes": {
        "category": "letterSpacing",
        "type": "1"
      },
      "path": [
        "letterSpacing",
        "1"
      ]
    },
    "2": {
      "value": "6%",
      "type": "letterSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "6%",
        "type": "letterSpacing"
      },
      "name": "LetterSpacing2",
      "attributes": {
        "category": "letterSpacing",
        "type": "2"
      },
      "path": [
        "letterSpacing",
        "2"
      ]
    },
    "3": {
      "value": "2%",
      "type": "letterSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "2%",
        "type": "letterSpacing"
      },
      "name": "LetterSpacing3",
      "attributes": {
        "category": "letterSpacing",
        "type": "3"
      },
      "path": [
        "letterSpacing",
        "3"
      ]
    },
    "4": {
      "value": "1%",
      "type": "letterSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "1%",
        "type": "letterSpacing"
      },
      "name": "LetterSpacing4",
      "attributes": {
        "category": "letterSpacing",
        "type": "4"
      },
      "path": [
        "letterSpacing",
        "4"
      ]
    }
  },
  "paragraphSpacing": {
    "0": {
      "value": "0",
      "type": "paragraphSpacing",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "0",
        "type": "paragraphSpacing"
      },
      "name": "ParagraphSpacing0",
      "attributes": {
        "category": "paragraphSpacing",
        "type": "0"
      },
      "path": [
        "paragraphSpacing",
        "0"
      ]
    }
  },
  "textCase": {
    "none": {
      "value": "none",
      "type": "textCase",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "none",
        "type": "textCase"
      },
      "name": "TextCaseNone",
      "attributes": {
        "category": "textCase",
        "type": "none"
      },
      "path": [
        "textCase",
        "none"
      ]
    },
    "uppercase": {
      "value": "uppercase",
      "type": "textCase",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "uppercase",
        "type": "textCase"
      },
      "name": "TextCaseUppercase",
      "attributes": {
        "category": "textCase",
        "type": "uppercase"
      },
      "path": [
        "textCase",
        "uppercase"
      ]
    },
    "small_caps_forced": {
      "value": "small_caps_forced",
      "type": "textCase",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "small_caps_forced",
        "type": "textCase"
      },
      "name": "TextCaseSmallCapsForced",
      "attributes": {
        "category": "textCase",
        "type": "small_caps_forced"
      },
      "path": [
        "textCase",
        "small_caps_forced"
      ]
    },
    "capitalize": {
      "value": "capitalize",
      "type": "textCase",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "capitalize",
        "type": "textCase"
      },
      "name": "TextCaseCapitalize",
      "attributes": {
        "category": "textCase",
        "type": "capitalize"
      },
      "path": [
        "textCase",
        "capitalize"
      ]
    }
  },
  "textDecoration": {
    "none": {
      "value": "none",
      "type": "textDecoration",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "none",
        "type": "textDecoration"
      },
      "name": "TextDecorationNone",
      "attributes": {
        "category": "textDecoration",
        "type": "none"
      },
      "path": [
        "textDecoration",
        "none"
      ]
    }
  },
  "paragraphIndent": {
    "0": {
      "value": "0px",
      "type": "dimension",
      "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
      "isSource": true,
      "original": {
        "value": "0px",
        "type": "dimension"
      },
      "name": "ParagraphIndent0",
      "attributes": {
        "category": "paragraphIndent",
        "type": "0"
      },
      "path": [
        "paragraphIndent",
        "0"
      ]
    }
  },
  "Heading": {
    "value": {
      "fontFamily": "Source Sans Pro",
      "fontSize": "11",
      "lineHeight": "56"
    },
    "type": "typography",
    "description": "Heading style",
    "filePath": "/Users/grahamclapham/Documents/APPS/style-guide-shootout/design-tokens/redhand-ui/design_token_converted/light_theme.json",
    "isSource": true,
    "original": {
      "value": {
        "fontFamily": "{fontFamilies.source-sans-pro}",
        "fontSize": "{fontSize.1}",
        "lineHeight": "{lineHeights.1}"
      },
      "type": "typography",
      "description": "Heading style"
    },
    "name": "Heading",
    "attributes": {
      "category": "Heading"
    },
    "path": [
      "Heading"
    ]
  }
});